app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/familymanagement
      username: cesar
      password: 'senha'
      pool-size: 30

server:
  error:
    include-binding-errors: always
    include-message: always

spring:
    sql:
      init:
        mode: always